// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_NQfL1U6xyZP0BV0PNVhvqQd2gqD_kY',
    appId: '1:976182926155:web:00ecee4c9796c98921e6ce',
    messagingSenderId: '976182926155',
    projectId: 'ownit-flutter',
    authDomain: 'ownit-flutter.firebaseapp.com',
    storageBucket: 'ownit-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-CGCVwdF4zmHw2hStsvXgeLjru1Y8BDs',
    appId: '1:976182926155:android:88be662d930e332b21e6ce',
    messagingSenderId: '976182926155',
    projectId: 'ownit-flutter',
    storageBucket: 'ownit-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm88IeVZfb6nkDT2OYnhgj3Ap4ktRmRBA',
    appId: '1:976182926155:ios:be4ce8044913167b21e6ce',
    messagingSenderId: '976182926155',
    projectId: 'ownit-flutter',
    storageBucket: 'ownit-flutter.firebasestorage.app',
    iosBundleId: 'com.example.ownIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm88IeVZfb6nkDT2OYnhgj3Ap4ktRmRBA',
    appId: '1:976182926155:ios:be4ce8044913167b21e6ce',
    messagingSenderId: '976182926155',
    projectId: 'ownit-flutter',
    storageBucket: 'ownit-flutter.firebasestorage.app',
    iosBundleId: 'com.example.ownIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8_NQfL1U6xyZP0BV0PNVhvqQd2gqD_kY',
    appId: '1:976182926155:web:00ecee4c9796c98921e6ce',
    messagingSenderId: '976182926155',
    projectId: 'ownit-flutter',
    authDomain: 'ownit-flutter.firebaseapp.com',
    storageBucket: 'ownit-flutter.firebasestorage.app',
  );
}
